POST http://localhost:3333/events
Content-Type: application/json

# Cabeçalhos
{
    "title": "Unite Summit 2024",
    "details":"Um evento para quem é apaixonado por programação",
    "maximumAttendees":100

}