POST http://localhost:3333/events
Content-Type: application/json

# Cabeçalhos
{
    "title": "Evento RoquetaSeat",
    "details":null,
    "maximumAttendees":100

}

###
# Register attendee on the event
POST http://localhost:3333/events/e7951e2c-0f05-42af-9dd1-fa16f5a80e1a/attendees
Content-Type: application/json

{
    "name": "Ednaldo Pereira",
    "email": "ednaldopereira.chansey@yahoo.com.br"
}

###

GET http://localhost:3333/events/4bb22458-f09e-497d-b47b-680d9948ab7c


###

GET http://localhost:3333/attendees/1/badge

###

#check in do usuário pelo id, então um mesmo usuário pode ter ids diferentes em eventos diferentes
GET http://localhost:3333/attendees/5/check-in

###

# get all attendees from event, which can be checked in or not
GET http://localhost:3333/events/e7951e2c-0f05-42af-9dd1-fa16f5a80e1a/attendees?query=pedro
